In [1]:
# read shapefile
import geopandas as gpd

In [2]:
species_df=gpd.read_file('new_species/ll_gda2020/esrishape/whole_of_dataset/victoria/FLORAFAUNA1/HDM_FAUNA_10M.shp')
species_df.head()

,CELL_ID,TAXON_ID,SCI_NAME,COMM_NAME,SUIT_PC,SUIT_HA,CELL_HA,SUITVCHA,SUVICPC,RECORD_SRC,TAXON_TYPE,IWS_IMAGE,VERS_DATE,geometry
0,467,10145,Charadrius australis,Inland Dotterel,None,25.31250,9901.05,2910.38,NaN,Habitat Distribution Model (within Native Veg),Other Non-passerine birds,vic-hdnv-v4-a10145_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.66667 -34.00000, 141.68333 -34.0..."
1,467,10236,Falco hypoleucos,Grey Falcon,None,12.09238,9901.05,135575.38,NaN,Habitat Distribution Model (within Native Veg),Other Non-passerine birds,vic-hdnv-v4-a10236_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.66667 -34.00000, 141.68333 -34.0..."
2,467,13207,Litoria raniformis,Growling Grass Frog,None,4679.98673,9901.05,2021294.19,NaN,Habitat Distribution Model (within Native Veg),Amphibians,vic-hdnv-v4-a13207_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.66667 -34.00000, 141.68333 -34.0..."
3,467,62921,Tympanocryptis lineata,Lined Earless Dragon,None,5.06250,9901.05,1265.06,NaN,Habitat Distribution Model (within Native Veg),Reptiles,vic-hdnv-v4-a62921_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.66667 -34.00000, 141.68333 -34.0..."
4,537,11061,Sminthopsis murina murina,Common Dunnart,None,6014.71145,6320.51,2445548.63,NaN,Habitat Distribution Model (within Native Veg),Mammals,vic-hdnv-v4-a11061_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((140.83333 -34.16667, 140.85000 -34.1..."

In [7]:
len(species_df)

30412

In [11]:
latitude=[species_df.iloc[i].geometry.centroid.y for i in range(len(species_df))]

longitude=[species_df.iloc[i].geometry.centroid.x for i in range(len(species_df)) ]

In [12]:
species_df['latitude']=latitude
species_df['longitude']=longitude

In [14]:
species_df.head(10)

,CELL_ID,TAXON_ID,SCI_NAME,COMM_NAME,SUIT_PC,SUIT_HA,CELL_HA,SUITVCHA,SUVICPC,RECORD_SRC,TAXON_TYPE,IWS_IMAGE,VERS_DATE,geometry,latitude,longitude
0,467,10145,Charadrius australis,Inland Dotterel,None,25.31250,9901.05,2910.38,NaN,Habitat Distribution Model (within Native Veg),Other Non-passerine birds,vic-hdnv-v4-a10145_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.66667 -34.00000, 141.68333 -34.0...",-34.083333,141.750000
1,467,10236,Falco hypoleucos,Grey Falcon,None,12.09238,9901.05,135575.38,NaN,Habitat Distribution Model (within Native Veg),Other Non-passerine birds,vic-hdnv-v4-a10236_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.66667 -34.00000, 141.68333 -34.0...",-34.083333,141.750000
2,467,13207,Litoria raniformis,Growling Grass Frog,None,4679.98673,9901.05,2021294.19,NaN,Habitat Distribution Model (within Native Veg),Amphibians,vic-hdnv-v4-a13207_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.66667 -34.00000, 141.68333 -34.0...",-34.083333,141.750000
3,467,62921,Tympanocryptis lineata,Lined Earless Dragon,None,5.06250,9901.05,1265.06,NaN,Habitat Distribution Model (within Native Veg),Reptiles,vic-hdnv-v4-a62921_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.66667 -34.00000, 141.68333 -34.0...",-34.083333,141.750000
4,537,11061,Sminthopsis murina murina,Common Dunnart,None,6014.71145,6320.51,2445548.63,NaN,Habitat Distribution Model (within Native Veg),Mammals,vic-hdnv-v4-a11061_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((140.83333 -34.16667, 140.85000 -34.1...",-34.250000,140.916667
5,537,10019,Turnix pyrrhothorax,Red-chested Button-quail,None,76.92524,6320.51,238612.44,NaN,Habitat Distribution Model (within Native Veg),Other Non-passerine birds,vic-hdnv-v4-a10019_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((140.83333 -34.16667, 140.85000 -34.1...",-34.250000,140.916667
6,538,12669,Furina diadema,Red-naped Snake,None,89.37074,28438.80,1175.31,NaN,Habitat Distribution Model (within Native Veg),Reptiles,vic-hdnv-v4-a12669_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.00000 -34.16667, 141.01667 -34.1...",-34.250000,141.083333
7,538,10497,Pyrrholaemus brunneus,Redthroat,None,10087.63699,28438.80,85285.75,NaN,Habitat Distribution Model (within Native Veg),Passerine birds,vic-hdnv-v4-a10497_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.00000 -34.16667, 141.01667 -34.1...",-34.250000,141.083333
8,539,10561,Climacteris affinis,White-browed Treecreeper,None,5556.91297,28438.80,99981.94,NaN,Habitat Distribution Model (within Native Veg),Passerine birds,vic-hdnv-v4-a10561_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.16667 -34.16667, 141.18333 -34.1...",-34.250000,141.250000
9,539,10111,Gelochelidon nilotica macrotarsa,Gull-billed Tern,None,116.43750,28438.80,985769.25,NaN,Habitat Distribution Model (within Native Veg),Waders,vic-hdnv-v4-a10111_2013sep27_thm_bio_75m_vg94.ecw,2014-05-02,"POLYGON ((141.16667 -34.16667, 141.18333 -34.1...",-34.250000,141.250000

In [18]:
map_sp_df=species_df.groupby(['latitude','longitude']).size().reset_index(name='counts')

In [19]:
map_sp_df.to_csv('map_sp_df.csv',index=False)